name: 🎯 Roadmap Initiative
description: Propose a new strategic initiative
title: ""
labels: ["initiative"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🗺️ Strategic Initiative
        Use this template to propose a new roadmap item with RASCI ownership and expected results.

        **📋 Need more structure?** Check our [template guide](https://github.com/namastexlabs/automagik-roadmap/tree/main/docs/templates):
        - **Minimal** (8 sections, 15-30min) - Small features, quick wins
        - **Standard** (12 sections, 1-2hr) - Most initiatives (recommended)
        - **Comprehensive** (20+ sections, 4-8hr) - Major launches, full PRD

        Or use our [CLI script](https://github.com/namastexlabs/automagik-roadmap/blob/main/scripts/create-initiative.sh) with templates for full control.

  - type: dropdown
    id: template_level
    attributes:
      label: Template Level (Optional)
      description: "Which template are you following? (helps workflows understand structure)"
      options:
        - "GitHub Form (this form)"
        - "Minimal Template"
        - "Standard Template"
        - "Comprehensive Template"
      default: 0

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which Automagik project does this initiative belong to?
      options:
        - omni
        - hive
        - spark
        - forge
        - genie
        - tools
        - cross-project
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What are we building and why? (Include problem context)
      placeholder: |
        **Problem:** Describe the problem or opportunity
        **Solution:** High-level approach
        **Impact:** Who benefits and how
    validations:
      required: true

  - type: textarea
    id: expected_results
    attributes:
      label: Expected Results (RESULTADO_ESPERADO)
      description: Measurable outcomes and success metrics
      placeholder: |
        - Increase X by Y%
        - Enable Z capability
        - Reduce P by Q
    validations:
      required: true

  - type: textarea
    id: success_criteria
    attributes:
      label: Success Criteria
      description: How will we know this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: markdown
    attributes:
      value: |
        ## 🚩 RASCI Ownership

  - type: input
    id: responsible
    attributes:
      label: Responsible
      description: "Who will lead execution? (1 person, use @username)"
      placeholder: "@username"
    validations:
      required: true

  - type: input
    id: accountable
    attributes:
      label: Accountable
      description: "Who has final approval? (1 person, use @username)"
      placeholder: "@username"
    validations:
      required: true

  - type: input
    id: support
    attributes:
      label: Support
      description: "Who will provide technical/operational support? (comma-separated @usernames)"
      placeholder: "@user1, @user2"

  - type: input
    id: consulted
    attributes:
      label: Consulted
      description: "Who should be consulted? (comma-separated @usernames or teams)"
      placeholder: "@user3, @team"

  - type: input
    id: informed
    attributes:
      label: Informed
      description: "Who should be kept informed? (comma-separated @usernames or teams)"
      placeholder: "@user4, @community"

  - type: markdown
    attributes:
      value: |
        ## 📊 Planning & Scheduling

  - type: dropdown
    id: stage
    attributes:
      label: Stage
      description: Current lifecycle stage
      options:
        - Wishlist
        - Ideation
        - Exploring
        - RFC
        - Priorization
        - Executing
        - Preview
        - Shipped
        - Archived
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Business priority
      options:
        - critical
        - high
        - medium
        - low
      default: 2
    validations:
      required: true

  - type: dropdown
    id: quarter
    attributes:
      label: Quarter (ETA)
      description: Target delivery quarter
      options:
        - backlog
        - 2025-q4
        - 2026-q1
        - 2026-q2
        - 2026-q3
        - 2026-q4
        - 2027-q1
      default: 0
    validations:
      required: true

  - type: input
    id: target_date
    attributes:
      label: Target Date (Optional)
      description: "Specific target date (YYYY-MM-DD)"
      placeholder: "2026-03-31"

  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Initiative type
      options:
        - feature
        - enhancement
        - research
        - infrastructure
        - documentation
      default: 0

  - type: input
    id: areas
    attributes:
      label: Areas (Optional)
      description: "Comma-separated areas (api, cli, mcp, workflows, agents, etc.)"
      placeholder: "api, mcp"

  - type: markdown
    attributes:
      value: |
        ## 🔗 References

  - type: input
    id: wish_folder
    attributes:
      label: Wish Folder (Optional)
      description: "Link to wish folder if already created"
      placeholder: "projects/omni/wishes/my-feature/"

  - type: textarea
    id: related_repos
    attributes:
      label: Related Repositories
      description: "Link to relevant repos/issues"
      placeholder: |
        - Implementation: namastexlabs/automagik-omni#123
        - Documentation: namastexlabs/automagik-docs#45
